name: Release Drafter

on:
  push:
    branches:
    - main
  workflow_dispatch: { }

concurrency:
  group: release-drafter-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-release-draft:
    name: Update release draft
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    # see https://github.com/release-drafter/release-drafter/issues/493#issuecomment-3686135286
    - name: Wait for 15 seconds to ensure GraphQL consistency
      shell: bash
      run: sleep 15s

    - uses: release-drafter/release-drafter@v6
      name: Update release draft
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
