name: Release Drafter

on:
  push:
    branches:
    - main
  workflow_dispatch: { }

permissions:
  contents: write
  pull-requests: write

jobs:
  update-release-draft:
    name: Update release draft
    runs-on: ubuntu-latest
    concurrency:
      group: update-release-draft
      cancel-in-progress: true
    steps:
    - uses: actions/github-script@v7
      name: Evaluate conditions
      id: conditions
      with:
        script: |
          const configFile = '.github/release-drafter.yml'
          const configFileExists = await github.rest.repos.getContent({
            owner: context.repo.owner,
            repo: context.repo.repo,
            path: configFile,
          }).then(
            () => true,
            error => { if (error.response && error.response.status === 404) return false; else throw error; }
          )
          if (!configFileExists) {
            core.info("Config file doesn't exist: " + configFile)
          }
          core.setOutput('exists', configFileExists ? 'true' : 'false')

          const repository = await github.rest.repos.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
          }).then(it => it.data)
          const isTemplate = !!repository.is_template
          if (isTemplate) {
            core.info("This repository is a template repository")
          }
          core.setOutput('isTemplate', isTemplate ? 'true' : 'false')

    - uses: release-drafter/release-drafter@v6
      name: Update release draft
      if: ${{fromJSON(steps.conditions.outputs.configFileExists)}}
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
